version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - /data/db
      - "$PWD/:/docker-entrypoint-initdb.d/"
    environment:
      MONGO_INITDB_DATABASE: aseProject
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pw



