version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - /data/db
    environment:
      MONGO_INITDB_DATABASE: aseProject
      MONGO_INITDB_ROOT_USERNAME: aseAdmin
      MONGO_INITDB_ROOT_PASSWORD: ase

