version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - "/data/db"
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      - MONGO_INITDB_DATABASE=aseProject
      - MONGO_INITDB_ROOT_USERNAME=aseAdmin
      - MONGO_INITDB_ROOT_PASSWORD=ase
    command: mongod --auth

  java-backend:
    image: angryfishproject/backend:latest
    ports:
      - "8080:8080"

  react-frontend:
    image: angryfishproject/frontend:latest
    ports:
      - "3000:3000"

  ngrok-frontend:
    image: wernight/ngrok
    environment:
      NGROK_PROTOCOL: http
      NGROK_PORT: 3000
      NGROK_LOOK_DOMAIN: "react-frontend"
    ports:
      - "4040:4040"

  ngrok-backend:
    image: wernight/ngrok
    environment:
      NGROK_AUTH: 2KxZh1JbE3CNitykVxg4w0StpxU_2pG59a9SUsc7UUC53fWm6
      NGROK_PROTOCOL: http
      NGROK_PORT: 8080
      NGROK_LOOK_DOMAIN: "java-backend"
    ports:
      - "4041:4040"